<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>WebSocket示例</title>
    <style>
    </style>
</head>
<body>
<div>消息内容</div>
<!--<textarea name="msgArea" id="msgArea" rows="20" cols="80"></textarea>-->
<br/><br/>
<input type="text" id="msg" size="80">
<input type="button" id="send-btn" value="发送消息" onclick="">
<input type="hidden" id="sequence" value="<?php echo $_REQUEST['sequence']?>">
<br/><br/>
</body>
<script src="/js/common/jquery-1.12.0.min.js"></script>
<script src="/js/ws/PlumeWS.js"></script>
<script src="/js/ws/openEvent.js"></script>
<script src="/js/ws/open.js?v=1"></script>
</html>
