<!-- qq客服 购物车 -->
<div style="width: 50px;bottom: 60px;position: fixed;z-index: 999;right: 20px;">
	<div class="hd-ke-text">
		<i class="iconfont">&#xe62a;</i>
		<span style="position: relative;top: 6px;left: -5px;">售前咨询</span>
	</div>
	<div class="hd-ke dingbu">
		<i class="iconfont" style="font-size: 30px;">&#xe60c;</i>
	</div>
	<div class="hd-ke shop">
		<i class="iconfont">&#xe61d;</i>
	</div>
	<div id="hd-qian" class="hd-ke qqkefu">
		<i class="iconfont">&#xe625;</i>
		<input type="hidden" value="1">
	</div>
	<div id="hd-hou" class="hd-ke qqkefu">
		<i class="iconfont">&#xe625;</i>
	</div>
</div>
<!-- 底部 -->
<footer id="footer">
	<div class="footer-warp">
		<ul>
			<li><i class="iconfont">&#xe620;</i>400-707-7100</li>
			<li><i class="iconfont" style="margin-top: -12px;">&#xe625;</i>1758894506</li>
			<li><i class="iconfont" style="margin-top: -12px;">&#xe625;</i>2141626725</li>
			<li>
    			<div class="footer_weixin">
    						<div class="weixe" style="height:208px; position: absolute;z-index: 100;margin-top: -200px;margin-left: -100px;display:none;">
    							<img style="width: 180px; " alt="" src="/img/layout/nhweix.png">
    						</div>
    						<i class="iconfont">&#xe61e;</i>
    			</div>
			互动大师</li>
			<li><i class="iconfont" style="margin-top: -12px;">&#xe61f;</i>hdds@infobird.com</li>
		</ul>
		<ul class="footer-two">
			<li>7×24小时热线</li>
			<li>售前咨询</li>
			<li>售前咨询</li>
			<li>关注微信公众号</li>
			<li>意见反馈</li>
		</ul>
	</div>
	<div class="footer-text">
		<span>Copyright ©2015 Guiyang Infobird Co.,Ltd. All rights reserved.黔ICP备14003224号</span>
	</div>
</footer>
</body>
<script>

</script>
</html>