<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="keywords" content="贵阳讯鸟">
    <meta name="description" content="互动大师">
    <link rel="stylesheet" href="/css/common/bootstrap.css" type="text/css" />
    <link rel="stylesheet" href="/css/common/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/common/bootstrap-theme.css" type="text/css" />
    <link rel="stylesheet" href="/css/common/bootstrap-theme.min.css" type="text/css" />
    <link rel="stylesheet" href="/css/layout/layout.css" type="text/css" />
    <link rel="stylesheet" href="/css/font/iconfont.css" type="text/css" />
    <script src="/js/common/jquery-1.12.0.js"></script>
    <script src="/js/common/jquery-1.12.0.min.js"></script>
    <script src="/js/common/bootstrap.js"></script>
    <script src="/js/common/bootstrap.min.js"></script>
    <link rel="shortcut icon" href="">
</head>
<style>
</style>
<body>

<script>
$().ready(function(){
	
})
</script>